version: '3'

services:
  app: # アプリ
    build:
      context: app
    ports:
      - "8080:8080"
    volumes:
      - ./app/views:/views/
      - ./app/public:/public/
      - ./app/log/:/log/
    depends_on:
      - mysql
    networks:
      - esnet

  mysql: # DBMS
    container_name: mysql_host
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - esnet

  es01:
    build:
      context: elasticsearch
    container_name: es01
    environment:
      node.name: es01
      discovery.seed_hosts: es02
      cluster.initial_master_nodes: es01,es02
      cluster.name: docker-cluster
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      http.cors.allow-origin: '*'
      http.cors.enabled: 'true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet
  es02:
    build:
      context: elasticsearch
    container_name: es02
    environment:
      node.name: es02
      discovery.seed_hosts: es01
      cluster.initial_master_nodes: es01,es02
      cluster.name: docker-cluster
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      http.cors.allow-origin: '*'
      http.cors.enabled: 'true'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql_host
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8081:80
    depends_on:
      - mysql
  
volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet: