version: '3'

services:
  app: # アプリ
    build:
      context: app
    ports:
      - "8080:8080"
      - "5051:5051"
    volumes:
      - ./app/views:/views/
      - ./app/public:/public/
      - ./app/log/:/log/
      - ./app/settings/:/settings/
      - ./app/.env/:/.env
    depends_on:
      mysql:
        condition: service_healthy
      es:
        condition: service_healthy
    networks:
      - esnet

  mysql: # DBMS
    container_name: mysql_host
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - esnet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      interval: 30s
      retries: 10
      start_period: 40s

  es:
    build:
      context: elasticsearch
    container_name: es
    environment:
      discovery.type: single-node
      cluster.name: docker-cluster
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      http.cors.allow-origin: '*'
      http.cors.enabled: 'true'
      xpack.security.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet
    healthcheck:
      test: curl -s http://es:9200/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
  
volumes:
  esdata:
    driver: local

networks:
  esnet:
