version: '3'

services:
  app: # アプリ
    image: ${TREE_APP_REPOSITORY_NAME}:latest
    ports:
      - "8080:8080"
      - "5051:5051"
    volumes:
      - ./app/.env/:/usr/src/app/.env
    environment:
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql_host:3306/hotate
      - APP_PORT=8080
      - WS_PORT=5051
      - ES_PORT=9200
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - esnet

  mysql: # DBMS
    container_name: mysql_host
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: hotate
      TZ: 'Asia/Tokyo'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - esnet
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      interval: 10s
      retries: 10
      start_period: 20s

volumes:
  dbdata:
    driver: local

networks:
  esnet:
