name: build
on:
  pull_request:
    paths:
      - 'app/**'

env:
  MYSQL_ROOT_PASSWORD: githubactions

jobs:
  app-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: app

    steps:
      - shell: bash
        run: |
          touch "${{ github.workspace }}/.env"
          echo "
            FOO=${{ secrets.TREE_SECRET }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            APP_PORT=${{ secrets.APP_PORT }}
            WS_PORT=${{ secrets.WS_PORT }}
            ES_PORT=${{ secrets.ES_PORT }}
            ES_DOCKER_NAME=${{ secrets.ES_DOCKER_NAME }}
            MYSQL_DOCKER_NAME=${{ secrets.MYSQL_DOCKER_NAME }}
          " >> "${{ github.workspace }}/.env"

      - name: checkout
        uses: actions/checkout@v2
      - name: build app
        run: docker-compose build app

      - name: run migrate
        run: docker-compose run --rm app npx prisma migrate dev
      
      - name: run tests
        run: docker-compose up -d app
