name: build
on:
  pull_request:
    paths:
      - 'app/**'
jobs:
  app-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build app
        run: docker-compose build app
      - name: compose up app
        run: docker-compose up -d app
