name: build
on: [pull_request]
jobs:
  app-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compose up app
        run: docker-compose up -d app
