name: build
on:
  push:
     branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compose up app
        run: docker-compoes up -d app