
name: markdownlint
on:
  pull_request:
    branches:
      - main
      - 'udpate-doc-*'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
