
name: markdownlint
on:
  pull_request:
    paths:
      - '**.md'
jobs:
  markdownlint-build:

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm init -y
      - run: npm i -g markdownlint-cli
      - run: markdownlint '**/*.md' -c './.markdownlint.jsonc'
      - if: failure()
        name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            markdownlintでエラーが発生しました。修正をお願いします :pray:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
