
name: markdownlint
on: [push]
jobs:
  markdownlint-build:

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Hello world ! :wave:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: npm init -y
      - run: npm i -g markdownlint-cli
      - run: markdownlint '**/*.md' --ignore node_modules
